In [38]:
import pandas as pd

In [39]:
df = pd.read_csv("/content/Training.csv")

In [40]:
df.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [41]:
df.shape

(4920, 133)

In [42]:
df["prognosis"].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [43]:
len(df["prognosis"].unique())

41

In [44]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

X = df.drop("prognosis", axis=1)
Y = df['prognosis']


In [45]:
X

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
0     ...                   0           0         0             0   
1     ...                   0           0         0             0   
2     ...                   0           0         0             0   
3     ...                   0           0         0             0   
4     ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
4915  ...                   0           0         0             0   
4916  ...                   1           1         1             0   
4917  ...                   0           0         0             0   
4918  ...                   0           0         0             1   
4919  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                       0                     0                   0        0   
1                       0                     0                   0        0   
2                       0                     0                   0        0   
3                       0                     0                   0        0   
4                       0                     0                   0        0   
...                   ...                   ...                 ...      ...   
4915                    0                     0                   0        0   
4916                    0                     0                   0        0   
4917                    0                     0                   0        0   
4918                    1                     1                   1        0   
4919                    0                     0                   0        1   

      red_sore_around_nose  yellow_crust_ooze  
0                        0                  0  
1                        0                  0  
2                        0                  0  
3                        0                  0  
4                        0                  0  
...                    ...                ...  
4915                     0                  0  
4916              

In [46]:
Y

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...                   
4915    (vertigo) Paroymsal  Positional Vertigo
4916                                       Acne
4917                    Urinary tract infection
4918                                  Psoriasis
4919                                   Impetigo
Name: prognosis, Length: 4920, dtype: object

In [47]:
train_test_split(X,Y,test_size = 0.3,random_state=20)

[      itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
 180         0          0                     0                    0   
 1910        0          0                     0                    0   
 2475        0          0                     0                    0   
 4278        1          0                     0                    0   
 709         0          0                     0                    0   
 ...       ...        ...                   ...                  ...   
 1607        0          1                     0                    0   
 3915        1          0                     0                    0   
 1428        0          0                     0                    0   
 4367        0          0                     0                    0   
 2522        0          0                     0                    0   
 
       shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
 180           0       1           0             0   

In [48]:
X_train,X_test,Y_Train,Y_Test = train_test_split(X,Y,test_size = 0.3,random_state=20)

In [49]:
X_train.shape

(3444, 132)

In [50]:
X_test.shape

(1476, 132)

In [51]:
Y_Train.shape

(3444,)

In [52]:
Y_Test.shape

(1476,)

In [53]:
le = LabelEncoder()
le.fit(Y)
y = le.transform(Y)

In [54]:
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np


In [55]:
models = {
    "SVC": SVC(kernel='linear'),
    "RandomForest": RandomForestClassifier(n_estimators=100, random_state=42),
    'GrandientBoosting': GradientBoostingClassifier(n_estimators=100, random_state=42),
    "KNeighbors": KNeighborsClassifier(n_neighbors=5),
    "MultinomialNB": MultinomialNB()
}

for model_name, model in models.items():
    model.fit(X_train,Y_Train)
    predictions = model.predict(X_test)
    accuracy = accuracy_score(Y_Test,predictions)
    cm = confusion_matrix(Y_Test, predictions)

    print(f"{model_name} accuracy : {accuracy}")
    print(f"{model_name} Confusion Matrix:")
    print(np.array2string(cm, separator=' '))

SVC accuracy : 1.0
SVC Confusion Matrix:
[[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ...
 [ 0  0  0 ... 34  0  0]
 [ 0  0  0 ...  0 41  0]
 [ 0  0  0 ...  0  0 31]]
RandomForest accuracy : 1.0
RandomForest Confusion Matrix:
[[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ...
 [ 0  0  0 ... 34  0  0]
 [ 0  0  0 ...  0 41  0]
 [ 0  0  0 ...  0  0 31]]
GrandientBoosting accuracy : 1.0
GrandientBoosting Confusion Matrix:
[[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ...
 [ 0  0  0 ... 34  0  0]
 [ 0  0  0 ...  0 41  0]
 [ 0  0  0 ...  0  0 31]]
KNeighbors accuracy : 1.0
KNeighbors Confusion Matrix:
[[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ...
 [ 0  0  0 ... 34  0  0]
 [ 0  0  0 ...  0 41  0]
 [ 0  0  0 ...  0  0 31]]
MultinomialNB accuracy : 1.0
MultinomialNB Confusion Matrix:
[[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ...
 [ 0  0  0 

In [56]:
# saving model
import pickle
import os

svc = SVC(kernel='linear',probability = True)
svc.fit(X_train, Y_Train)

os.makedirs("models", exist_ok=True)
pickle.dump(svc, open("models/svc.pkl", 'wb'))

# load model
svc = pickle.load(open("models/svc.pkl", 'rb'))


In [57]:
# test 1
print("Predicted Label :", svc.predict(X_test.iloc[0].values.reshape(1, -1)))
print("Actual Label :" , Y_Test.iloc[0])

Predicted Label : ['hepatitis A']
Actual Label : hepatitis A


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [58]:
X_test

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
4037        0          0                     0                    0   
4191        0          0                     0                    0   
432         0          0                     0                    0   
1266        1          0                     0                    0   
3765        0          0                     0                    0   
...       ...        ...                   ...                  ...   
2837        0          0                     0                    0   
2327        0          0                     0                    0   
1399        1          1                     0                    0   
1906        0          0                     0                    1   
4474        0          0                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
4037          0       0           1             0        0                 0   
4191          0       0           0             0        0                 0   
432           0       0           0             1        1                 0   
1266          0       0           0             0        0                 0   
3765          0       0           1             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
2837          0       0           0             0        0                 0   
2327          0       1           0             0        0                 0   
1399          0       0           0             0        0                 0   
1906          0       1           0             0        0                 0   
4474          0       0           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
4037  ...                   0           0         0             0   
4191  ...                   0           0         0             0   
432   ...                   0           0         0             0   
1266  ...                   0           0         0             0   
3765  ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
2837  ...                   0           0         0             0   
2327  ...                   0           0         0             0   
1399  ...                   0           0         0             0   
1906  ...                   0           0         0             0   
4474  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
4037                    0                     0                   0        0   
4191                    0                     0                   0        0   
432                     0                     0                   0        0   
1266                    0                     0                   0        0   
3765                    0                     0                   0        0   
...                   ...                   ...                 ...      ...   
2837                    0                     0                   0        0   
2327                    0                     0                   0        0   
1399                    0                     0                   0        0   
1906                    0                     0                   0        0   
4474                    0                     0                   0        0   

      red_sore_around_nose  yellow_crust_ooze  
4037                     0                  0  
4191                     0                  0  
432                      0                  0  
1266                     0                  0  
3765                     0                  0  
...                    ...                ...  
2837                     0                  0  
2327              

In [59]:
# test 2
print("Predicted Label :", svc.predict(X_test.iloc[88].values.reshape(1, -1)))
print("Actual Label :" , Y_Test.iloc[88])


Predicted Label : ['Arthritis']
Actual Label : Arthritis


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [60]:
sym_disease = pd.read_csv("/content/symtoms_df.csv")
precautions = pd.read_csv("/content/precautions_df.csv")
workout = pd.read_csv("/content/workout_df.csv")
description = pd.read_csv("/content/description.csv")
medication = pd.read_csv("/content/medications.csv")
diet = pd.read_csv("/content/diets.csv")
severity = pd.read_csv("/content/Symptom-severity.csv")

In [61]:
description.shape


(41, 2)

In [62]:
def helper(dis):
    # Get description
    desc = description[description['Disease'] == dis]['Description']
    desc = " ".join([w for w in desc])

    # Get precautions
    pre = precautions[precautions['Disease'] == dis][['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']]
    pre = [col for col in pre.values]

    # Parse medication string list
    med = medication[medication['Disease'] == dis]['Medication'].values
    if len(med) > 0:
        med = med[0].strip("[]").replace("'", "").split(", ")
    else:
        med = ["No data available"]

    # Parse diet string list
    die = diet[diet['Disease'] == dis]['Diet'].values
    if len(die) > 0:
        die = die[0].strip("[]").replace("'", "").split(", ")
    else:
        die = ["No data available"]

    # Get workout list as flat list
    wrkout = workout[workout['disease'] == dis]['workout'].values.tolist()
    if len(wrkout) == 0:
        wrkout = ["No data available"]

    # Return all info
    return desc, pre, med, die, wrkout

symptoms_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}
diseases_list = {15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}
severity_dict = dict(zip(severity['Symptom'].str.lower(),severity['weight']))

def get_predicted_value(patient_symptoms):
    input_vector = np.zeros(len(symptoms_dict))
    for item in patient_symptoms:
        item=item.strip().lower()
        if item in symptoms_dict:
          index = symptoms_dict[item]
          weight = severity_dict.get(item, 1)
          input_vector[index] = weight
        else:
            print(" Warning: '{item}' not found in symptoms dictionary.")
    return svc.predict([input_vector])[0]

In [63]:
def show_top_predictions(patient_symptoms, model, n=3):
    input_vector = np.zeros(len(symptoms_dict))
    for item in patient_symptoms:
        item = item.strip().lower()
        if item in symptoms_dict:
            index = symptoms_dict[item]
            weight = severity_dict.get(item, 1)
            input_vector[index] = weight

    probas = model.predict_proba([input_vector])[0]
    top_n = probas.argsort()[-n:][::-1]
    print("\n Top Predicted Diseases:")
    for i in top_n:
        print(f"- {model.classes_[i]} ({probas[i]*100:.2f}%)")

In [72]:
symptoms = input("Enter your symptoms (comma-separated): ")
user_symptoms = [s.strip().lower() for s in symptoms.split(',')]

# Predict top diseases with confidence
def show_top_predictions(patient_symptoms, model, n=3):
    input_vector = np.zeros(len(symptoms_dict))
    for item in patient_symptoms:
        if item in symptoms_dict:
            index = symptoms_dict[item]
            weight = severity_dict.get(item, 1)
            input_vector[index] = weight
    probas = model.predict_proba([input_vector])[0]
    top_n = probas.argsort()[-n:][::-1]
    print("\n Top Predicted Diseases:")
    for i in top_n:
        print(f"- {model.classes_[i]} ({probas[i]*100:.2f}%)")

# Show top 3 predictions
show_top_predictions(user_symptoms, svc)

# Predict final disease label
predicted_disease = get_predicted_value(user_symptoms)

# Recommendations
desc, pre, med, die, wrkout = helper(predicted_disease)

# Output
print("=================predicted disease============")
print(predicted_disease)
print("=================description==================")
print(desc)

print("=================precautions==================")
i = 1
for p_i in pre[0]:
    print(i, ": ", p_i)
    i += 1

print("=================medications==================")
for m_i in med:
    print(i, ": ", m_i)
    i += 1

print("=================workout==================")
for w_i in wrkout:
    print(i, ": ", w_i)
    i += 1

print("=================diets==================")
for d_i in die:
    print(i, ": ", d_i)
    i += 1

Enter your symptoms (comma-separated): acidity,muscle wasting

 Top Predicted Diseases:
- GERD (27.94%)
- Migraine (5.43%)
- Fungal infection (4.91%)
=================predicted disease============
GERD
=================description==================
GERD (Gastroesophageal Reflux Disease) is a digestive disorder that affects the lower esophageal sphincter.
=================precautions==================
1 :  avoid fatty spicy food
2 :  avoid lying down after eating
3 :  maintain healthy weight
4 :  exercise
=================medications==================
5 :  Proton Pump Inhibitors (PPIs)
6 :  H2 Blockers
7 :  Antacids
8 :  Prokinetics
9 :  Antibiotics
=================workout==================
10 :  Consume smaller meals
11 :  Avoid trigger foods (spicy, fatty)
12 :  Eat high-fiber foods
13 :  Limit caffeine and alcohol
14 :  Chew food thoroughly
15 :  Avoid late-night eating
16 :  Consume non-citrus fruits
17 :  Include lean proteins
18 :  Stay hydrated
19 :  Avoid carbonated beverages
=

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [67]:
predicted_disease

'Fungal infection'

In [68]:
import sklearn
print(sklearn.__version__)

1.6.1
